blogs/urls.py
from django.conf.urls import url
from . import views

app_name = "blogs"
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blogs.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

]

blogs/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)
        
    def publish(self):
        self.published_date = timezone.now()
        self.save()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

class File(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='files')
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=250)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

blogs/forms.py
from django import forms
from .models import Post ,Comment ,File

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('author', 'text',)

class UploadFileForm(forms.Form):
    file = forms.FileField(required=False)

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Comment, File
from .forms import PostForm, CommentForm, UploadFileForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def post_list(request):
    posts_list = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(posts_list, 5)
    pageNumber = request.GET.get('page')
    try:
        posts = paginator.page(pageNumber)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'posts': posts})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})
    
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments_list = post.comments.filter(post_id=pk)
    paginator = Paginator(comments_list, 5)
    pageNumber = request.GET.get('page')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blogs:post_detail', pk=post.pk)
    else:
        form = CommentForm()

    try:
        comments = paginator.page(pageNumber)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_detail.html', {'post': post,'form':form,'comments':comments})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        formfile = UploadFileForm(request.POST, request.FILES)
        if ( form.is_valid() and formfile.is_valid() ):
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            postid = get_object_or_404(Post, pk=post.pk)
            upload(request.FILES['file'])
            file = File()
            file.post = postid
            file.title = request.POST['title']
            file.link = '/static/upload/'+request.FILES['file'].name
            file.save()

            return redirect('blogs:post_detail', pk=post.pk)
    else:
        form = PostForm()
        formfile = UploadFileForm()

    return render(request, 'blog/post_edit.html', {'form': form, 'formfile':formfile})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk) 
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        formfile = UploadFileForm(request.POST, request.FILES)
        if formfile.is_valid():
            upload(request.FILES['file'])
            file = File()
            file.post = post
            file.title = request.POST['title']
            file.link = '/static/upload/'+request.FILES['file'].name
            file.save()
            
        if form.is_valid():    
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            return redirect('blogs:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
        formfile = UploadFileForm()

    return render(request, 'blog/post_edit.html', {'form': form, 'formfile':formfile})

def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()

    return redirect('blogs:post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()

    return redirect('blogs:post_list')


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blogs:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blogs:post_detail', pk=comment.post.pk)

def upload(f): 
    file = open('blogs/static/upload/'+f.name, 'wb+') 
    for chunk in f.chunks():
        file.write(chunk)

blogs/templates/blog/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
        {% comment %}<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">{% endcomment %}
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <title>Vinh's' blog</title>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-page">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">VINH's Blog</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li {% block addnew %}{% endblock %}>
                        <a href="{% url 'blogs:post_new' %}">Add New</a>
                    </li>
                    <li {% block draft %}{% endblock %}>
                        <a href="{% url 'blogs:post_draft_list' %}">Draft List</a>
                    </li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'logout' %}">Log out</a></li>
                </ul>
                <p class="navbar-text navbar-right"> Wellcome {{ user.username }} </p>
                
                {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li {% block login %}{% endblock %}><a href="{% url 'login' %}"><span class="glyphicon glyphicon-lock"></span> Login</a></li>
                </ul>
                {% endif %}
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <h3>About</h3>
                        This blog is dedicated to provide quality tutorials on various programming language. If you want to cooperate, write articles...
                        <br>Plz contact us: nguyendangvinh_92dn@yahoo.com <br>
                    </div>
                </div>
            </div>
        </footer>
        <div class="copyright">
            <div class="container">
                © 2017 vinhnguyen.com
            </div>
        </div>
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
</html>

blogs/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% for file in post.files.all %}
        <img src="{{ file.link }}" alt="blog">
        {% endfor %}
        <h3>{{ post.title }}</h3>
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blogs:post_publish' pk=post.pk %}">Publish</a>
        {% endif %}

        {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'blogs:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'blogs:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% endif %}
        <p>{{ post.text|safe|linebreaksbr }}</p>
    </div>
    <hr>
    {% for comment in comments %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="media">
                <div class="media-left">
                    <a>
                        <img class="media-object" src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQd38655KckV2T9IRMsiU7w7oHCsO-qQzIYQydk-W-DypxnG5h5" alt="blog" style="width: 40px">
                    </a>
                </div>
                <div class="media-body">
                    {% if not comment.approved_comment %}
                    <div style="float: right">
                        <a class="btn btn-default" href="{% url 'blogs:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                        <a class="btn btn-default" href="{% url 'blogs:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                    </div>
                    {% endif %}                                      
                    <h4 class="media-heading">{{ comment.author }} <span class="badge">{{ comment.created_date }}</span></h4>
                    <p>{{ comment.text|linebreaks }}</p>
                </div>
            </div>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
    {% if comments.has_other_pages %}
        <div class="pagination_page">
            <ul class="pagination">
                {% if comments.has_previous %}
                    <li>
                        <a href="?page={{ comments.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">«</span></a>
                    </li>
                    {% else %}
                    <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                {% endif %}
                
                {% for i in comments.paginator.page_range %}
                    {% if comments.number == i %}
                        <li class="active"><a>{{ i }}</a></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if comments.has_next %}
                    <li>
                        <a href="?page={{ comments.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a>
                    </li>
                    {% else %}
                    <li class="disabled"><a aria-label="Next"><span aria-hidden="true">»</span></a></li>
                {% endif %}
            </ul>       
        </div>
    {% endif %}
    <hr>
    <h3>New comment</h3>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Add Comment</button>
    </form>
{% endblock %}

blogs/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block draft %}class="active"{% endblock %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blogs:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blogs/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block addnew %}class="active"{% endblock %}
{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ formfile.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

blogs/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}       
        <div class="list_post media">
            <div class="media-left">
                <a href="{% url 'blogs:post_detail' pk=post.pk %}">
                {% for file in post.files.all %}
                    <img class="media-object" src="{{ file.link }}" alt="blog">
                {% endfor %}
                </a>
            </div>
            <div class="media-body">
                <div class="post">                  
                    <h4 class="media-heading"><a href="{% url 'blogs:post_detail' pk=post.pk %}">{{ post.title }}</a></h4>
                    <div class="date">
                        <p>
                            <span>published: {{ post.published_date }}</span>
                            <span><a href="{% url 'blogs:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a></span>
                        </p>                        
                    </div>
                    <p>{{ post.text|truncatechars:250 }}</p>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if posts.has_other_pages %}
    <div class="pagination_page">
        <ul class="pagination">
            {% if posts.has_previous %}
                <li>
                    <a href="?page={{ posts.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">«</span></a>
                </li>
                {% else %}
                <li class="disabled"><a aria-label="Previous"><span aria-hidden="true">«</span></a></li>
            {% endif %}
            
            {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                    <li class="active"><a>{{ i }}</a></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if posts.has_next %}
                <li>
                    <a href="?page={{ posts.next_page_number }}" aria-label="Next"><span aria-hidden="true">»</span></a>
                </li>
                {% else %}
                <li class="disabled"><a aria-label="Next"><span aria-hidden="true">»</span></a></li>
            {% endif %}
        </ul>       
    </div>
    {% endif %}
{% endblock %}